### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by yunhochung** [Consensys-Incorporated/tessera#1087] opened 2020-06-16 10:44 UTC
Hi!!
I got the OOM(Out of Memory) error yesterday. 
So, I did add APM agent for heap monitoring to Tessera.

I found the memory leak as below link. (sample..)
(I'm sorry. I can't post the real graph because the company policy)

Heap memory usage is increasing gradually after GC on all node.
https://i.stack.imgur.com/NlsbR.jpg

Heap memory is increased 130MB for 8 hours.

Thank you.

**Comment by namtruong** [comment] 2020-06-16 11:50
Hi,

Can you give details of the specs the Tessera nodes ? How much memory was given to each?

Thanks,

**Comment by yunhochung** [comment] 2020-06-16 14:03
Hi,
Tessera version is 0.10.5 and is running on Docker container with AWS ECS.

- Container Memory: 1024M
- JVM Option: -Xms768M -Xmx768M

There are a little transaction between nodes.

Thank you.

**Comment by namtruong** [comment] 2020-06-16 14:17
Thanks.

With the above memory allocated and little transaction volume, getting OOO is unusual.

Could you please post the error log when ooo occurs ?

**Comment by yunhochung** [comment] 2020-06-16 14:24
@namtruong I have no error log because I didn't config for heapdump. Currently, all node's heap memory is increasing gradually after re-set up for heap dump. So, I'm getting heap dump log.

**Comment by namtruong** [comment] 2020-06-16 14:41
ok - please send us some logs when you have.

How many nodes are you running currently ? What are the volume of transactions roughly ? Are they all private and signed externally ?

I'll also try to replicate from my end - although we've seen networks running very long under heavy load with less memory allocated, so there might something unusual happening.

**Comment by yunhochung** [comment] 2020-06-16 14:57
- How many nodes are you running currently ? 
   -> 4 validators, 9 geth+tessera nodes
- What are the volume of transactions roughly ? 
   -> 16,000 tx / 600,000 blocks
- Are they all private and signed externally ?
  -> all nodes are sending private/public transaction

Thank you.

**Comment by yunhochung** [comment] 2020-06-17 08:00
@namtruong I got the heap dump from all nodes and ran IBM Heap Analyzer..
I found common some leak suspect as below.
But, I can't find the reference object(tree) on IBM Heap Analyzer.

- org/postgresql/jdbc/PgConnection
  -> Instances Count: >500
  -> heap Size: 280M

- java/util/concurrent/ConcurrentSkipListMap$index, $Node
  -> Instances Count: > 6,000
  -> Heap Size: 210M

Thank you.

**Comment by namtruong** [comment] 2020-06-17 10:03
@yunhochung Thanks for these.

We'll investigate and get back in due course

**Comment by namtruong** [comment] 2020-06-18 09:39
What's the version of postgresql jdbc driver you're using ?

Also any luck with any exceptions in the logs ?

**Comment by yunhochung** [comment] 2020-06-18 11:44
@namtruong JDBC driver version is 42.2.14 from https://jdbc.postgresql.org/download.html. There is no exception. :( All node's heap is still increasing after restarting tessera.

**Comment by namtruong** [comment] 2020-06-26 15:25
@yunhochung I've been trying to replicate the issue on my end but haven't been successful so far.

The infrastructure given seems to be more than enough for a Tessera node to perform under heavy load

Are you able to reproduce this issue on a different environment, and perhaps help us by sharing more logs or any exceptions that ever occurred?

**Comment by yunhochung** [comment] 2020-06-30 04:09
@namtruong I'm sorry that I can't reproduce this issue on other environment. I did recently add new node(Memory: 1G, Heap: 768M) to network with ECS(Elastic Container Service). This new node's memory is also increasing gradually. Have you been testing the Tessra with 1G memory, 768M heap???

**Comment by namtruong** [comment] 2020-07-01 09:55
Hi @yunhochung we've been testing Tessera with less heap given i.e. `-Xms512M -Xmx512M` . If this is not possible to reproduce in a different environment the issue might be more container-related than Tessera itself.

I haven't been able to try the latest Tessera on ECS (I did a while ago though) - however with containers we usually allow 4G of memory for them. So perhaps you can try to allocate more memory (4GB) to the ECS tasks and see if the issue still persists ?

Thanks,
Nam

**Comment by yunhochung** [comment] 2020-07-02 04:52
Hi~ @namtruong Thank you for your support. :) I think that it's rarely related to ECS. ECS is just managing docker container.
(A container is running with 1GMemory. A tessera is is running 768M Heap.)
Can I see your used Heap graph for 2-3 days if you don't mind?
Have you been seen the # of instances in Heap dump as below?
* org/postgresql/jdbc/PgConnection
-> Instances Count: >500
-> heap Size: 280M

* java/util/concurrent/ConcurrentSkipListMap$index, $Node
-> Instances Count: > 6,000
-> Heap Size: 210M

Thank you.

**Comment by yunhochung** [comment] 2020-07-20 04:21
@namtruong Hi! Can you update the status regarding this issue??

**Comment by namtruong** [comment] 2020-07-20 07:43
@yunhochung Apologies for delay in getting back to you. I'll try to have a long running network and gather the heap graph and post it on here.

Also I saw the objects you mentioned however they got garbage collected and the number of instances don't grow that much.

In the meantime, have you got any luck with the steps to reproduce the issue on a different environment? Also did you try to allocate more memory for the container (i.e. 4GB) ?

**Comment by namtruong** [comment] 2020-07-24 14:43
<img width="1151" alt="heap-tracer" src="https://user-images.githubusercontent.com/8926823/88402858-9cba6700-cdc3-11ea-99bb-07cf7f2eac99.png">
<img width="1151" alt="normal" src="https://user-images.githubusercontent.com/8926823/88402876-a348de80-cdc3-11ea-89d3-3daecf0e9516.png">
<img width="1151" alt="under-high-stress" src="https://user-images.githubusercontent.com/8926823/88402894-a80d9280-cdc3-11ea-9746-6dfd20c77f23.png">

Please see the heap graphs captured above on my local test network. The last graph is the heap usage when Tessera was under stress testing.

Each Tessera node was given `-Xms256M -Xmx256M` and also used postgresql for db.

There were about 250K transactions sent during the period.

**Comment by namtruong** [comment] 2020-07-24 14:50
I will now close this as we're not able to reproduce the issue you were having.

We would try our best to support if you can test this issue in a different environment and provide the steps to replicate. Otherwise my suggestion for now would be to increase the memory given to the container process (i.e. 4GB instead of 1GB).

**Closed as completed by namtruong** 2020-07-24 14:50 UTC
Labels: review
